ALTER TABLE workouts ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ;
ALTER TABLE workouts ADD COLUMN IF NOT EXISTS ended_at TIMESTAMPTZ;
ALTER TABLE sets ADD COLUMN IF NOT EXISTS done BOOLEAN NOT NULL DEFAULT FALSE;
